spring:
    datasource:
        url: jdbc:oracle:thin:@113.106.11.112:1251:orcl
        ##url: jdbc:oracle:thin:@192.168.18.42:1521:orcl
        #数据库账户
        username: quality_test
        #数据库密码
        password: life123456
tcp:
    port: 8089