-- we don't know how to generate schema QUALITY_TEST (class Schema) :(
create sequence BAD_CODE_SEQ
  cache 10
/

create sequence PROCESS_SEQ
  cache 10
/

create sequence PROCESS_RECORD_SEQ
  cache 10
/

create sequence PRODUCT_SEQ
  cache 10
/

create sequence PRODUCT_LINE_SEQ
  cache 10
/

create sequence PRODUCT_TYPE_SEQ
  cache 10
/

create sequence QA_USER_SEQ
  cache 10
/

create sequence REPAIR_RECORD_SEQ
  cache 10
/

create sequence QA_ROLE_SEQ
  cache 10
/

create sequence SYS_LOG_SEQ
  cache 10
/

create sequence WORK_SHEET_SEQ
  cache 10
/

create sequence BOM_SEQ
  cache 10
/

create sequence SN_INFO_SEQ
  cache 10
/

create table BAD_CODE
(
  ID NUMBER(11) not null
    constraint PK_BAD_CODE
    primary key,
  PROCESS_CODE VARCHAR2(80),
  CODE VARCHAR2(80),
  NAME VARCHAR2(200),
  REMARK VARCHAR2(400),
  VALID NUMBER default 0,
  constraint AK_UQ_BAD_CODE_BAD_CODE
  unique (PROCESS_CODE, CODE)
);
COMMENT ON TABLE BAD_CODE IS'不良代码';
COMMENT ON COLUMN BAD_CODE.ID IS'主键';
COMMENT ON COLUMN BAD_CODE.PROCESS_CODE IS'站别代码';
COMMENT ON COLUMN BAD_CODE.CODE IS'不良代码';
COMMENT ON COLUMN BAD_CODE.NAME IS'备注内容';
COMMENT ON COLUMN BAD_CODE.REMARK IS'备注内容';
COMMENT ON COLUMN BAD_CODE.VALID IS'是否有效，0有效，1无效';
/

create table PROCESS
(
  ID NUMBER(20) default NULL not null
    constraint PK_PROCESS
    primary key,
  TYPE NUMBER(1) default NULL,
  CODE VARCHAR2(80),
  NAME VARCHAR2(80),
  SNTREGEX VARCHAR2(80),
  REMARK VARCHAR2(80),
  VALID NUMBER default 0,
  CLASSIFY NUMBER default 0,
  constraint AK_UQ_PROCESS_TYPE_CO_PROCESS
  unique (TYPE, CODE)
);

COMMENT ON TABLE PROCESS IS'站别';
COMMENT ON COLUMN PROCESS.ID IS'主键';
COMMENT ON COLUMN PROCESS.TYPE IS'站别类型（0,process,1,repair）';
COMMENT ON COLUMN PROCESS.CODE IS'站别代码';
COMMENT ON COLUMN PROCESS.NAME IS'站别名称';
COMMENT ON COLUMN PROCESS.REMARK IS'备注内容';
COMMENT ON COLUMN PROCESS.VALID IS'是否有效，0有效，1无效';
/

create table PROCESS_FLOW
(
  PRODUCT_TYPE_CODE VARCHAR2(80) not null,
  PROCESS_CODE VARCHAR2(80) not null,
  NEXT_PROCESS_CODE VARCHAR2(80),
  REPAIR_PROCESS_CODE VARCHAR2(80)
);
COMMENT ON TABLE PROCESS_FLOW IS'站别流程';
COMMENT ON COLUMN PROCESS_FLOW.PRODUCT_TYPE_CODE IS'产品类型';
COMMENT ON COLUMN PROCESS_FLOW.PROCESS_CODE IS'站别代码';
COMMENT ON COLUMN PROCESS_FLOW.REPAIR_PROCESS_CODE IS'维修站别code';
COMMENT ON COLUMN PROCESS_FLOW.NEXT_PROCESS_CODE IS'下一工作站';
/

create table PROCESS_RECORD
(
  ID NUMBER(20) default NULL not null
    constraint PK_PROCESS_RECORD
    primary key,
  PRODUCT_ID NUMBER(11),
  PRODUCT_LINE VARCHAR2(80),
  PROCESS_CODE VARCHAR2(80),
  STATUS VARCHAR2(80),
  USER_ID NUMBER(11),
  DESCRIPTION VARCHAR2(200),
  CONTENT_JSON VARCHAR2(1000),
  CREATE_TIME DATE default SYSDATE
);
COMMENT ON TABLE PROCESS_RECORD IS'测试记录';
COMMENT ON COLUMN PROCESS_RECORD.ID IS'主键';
COMMENT ON COLUMN PROCESS_RECORD.PRODUCT_ID IS'产品id';
COMMENT ON COLUMN PROCESS_RECORD.PRODUCT_LINE IS'线别';
COMMENT ON COLUMN PROCESS_RECORD.PROCESS_CODE IS'站别代号';
COMMENT ON COLUMN PROCESS_RECORD.status IS'状态，0OK，1其他，-1NG';
COMMENT ON COLUMN PROCESS_RECORD.user_id IS'用户Id';
COMMENT ON COLUMN PROCESS_RECORD.description IS'描述';
COMMENT ON COLUMN PROCESS_RECORD.content_json IS'测试内容json';
COMMENT ON COLUMN PROCESS_RECORD.CREATE_TIME IS'创建时间';
/

create table PRODUCT
(
  ID NUMBER(20) default NULL not null
    constraint PK_PRODUCT
    primary key,
  SHEET_PO VARCHAR2(80),
  PRODUCT_NO VARCHAR2(80),
  PRODUCT_TYPE_CODE VARCHAR2(80),
  CPSN VARCHAR2(80)
    constraint AK_UQ_PRODUCT_CPSN_PRODUCT
    unique,
  BLSN VARCHAR2(80)
    constraint AK_UQ_PRODUCT_BLSN_PRODUCT
    unique,
  BBSN VARCHAR2(80)
    constraint AK_QU_PRODUCT_BBSN_PRODUCT
    unique,
  CGQSN VARCHAR2(80),
  SMSSN VARCHAR2(80),
  BXKSN VARCHAR2(80),
  CHSN VARCHAR2(80),
  VALID NUMBER(1),
  CREATE_TIME DATE,
  MODIFY_TIME DATE default SYSDATE
);

COMMENT ON TABLE PRODUCT IS'产品';
COMMENT ON COLUMN PRODUCT.ID IS'主键';
COMMENT ON COLUMN PRODUCT.SHEET_NO IS'工单号';
COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS'产品编号';
COMMENT ON COLUMN PRODUCT.PRODUCT_TYPE_CODE IS'产品类型';
COMMENT ON COLUMN PRODUCT.CPSN IS'产品SN码';
COMMENT ON COLUMN PRODUCT.BLSN IS'玻璃SN';
COMMENT ON COLUMN PRODUCT.BBSN IS'板板sn';
COMMENT ON COLUMN PRODUCT.CGQSN IS'传感器';
COMMENT ON COLUMN PRODUCT.SMSSN IS'说明书sn';
COMMENT ON COLUMN PRODUCT.BXKSN IS'保修卡sn';
COMMENT ON COLUMN PRODUCT.CHSN IS'彩盒sn';
COMMENT ON COLUMN PRODUCT.VALID IS'是否有效（0有效，1无效）';
COMMENT ON COLUMN PRODUCT.CREATE_TIME IS'创建时间';
COMMENT ON COLUMN PRODUCT.MODIFY_TIME IS'修改时间';
/

create table PRODUCT_LINE
(
  ID NUMBER(20) default NULL not null
    constraint PK_PRODUCT_LINE
    primary key,
  CODE VARCHAR2(80)
    constraint AK_UQ_PRODUCT_LINE_PRODUCT_
    unique,
  NAME VARCHAR2(200),
  REMARK VARCHAR2(400),
  VALID NUMBER default 0
);

COMMENT ON TABLE PRODUCT_LINE IS'线别';
COMMENT ON COLUMN PRODUCT_LINE.ID IS'主键';
COMMENT ON COLUMN PRODUCT_LINE.CODE IS'线别代码';
COMMENT ON COLUMN PRODUCT_LINE.NAME IS'线别名称';
COMMENT ON COLUMN PRODUCT_LINE.REMARK IS'备注内容';
COMMENT ON COLUMN PRODUCT_LINE.VALID IS'是否有效，0有效，1无效';
/

create table PRODUCT_TYPE
(
  ID NUMBER(20) default NULL not null
    constraint PK_PRODUCT_TYPE
    primary key,
  CODE VARCHAR2(80) not null
    constraint AK_UQ_PRODUCT_TYPE_PRODUCT_
    unique,
  NAME VARCHAR2(80),
  VALID NUMBER(1)
);
COMMENT ON TABLE PRODUCT_TYPE IS'备注内容';
COMMENT ON COLUMN PRODUCT_TYPE.ID IS'主键';
COMMENT ON COLUMN PRODUCT_TYPE.CODE IS'产品型号代码';
COMMENT ON COLUMN PRODUCT_TYPE.NAME IS'产品名称';
COMMENT ON COLUMN PRODUCT_TYPE.VALID IS'是否有效，0有效，1无效';
/

create table QA_USER
(
  ID NUMBER(20) default NULL not null
    constraint PK_QA_USER
    primary key,
  ACCOUNT VARCHAR2(80)
    constraint AK_UQ_OA_USER_QA_USER
    unique,
  PASSWORD VARCHAR2(80),
  CODE VARCHAR2(80),
  NAME VARCHAR2(80),
  PROCESS_CODE VARCHAR2(80),
  PROCESS_SIGN NUMBER default 0,
  VALID NUMBER default 0,
  CREATE_USER_ID NUMBER(20),
  CREATE_TIME DATE default SYSDATE,
  MODIFY_TIME DATE
);

COMMENT ON TABLE QA_USER IS'用户';
COMMENT ON COLUMN QA_USER.ID IS'主键';
COMMENT ON COLUMN QA_USER.ACCOUNT IS'账户';
COMMENT ON COLUMN QA_USER.PASSWORD IS'密码';
COMMENT ON COLUMN QA_USER.CODE IS'工号';
COMMENT ON COLUMN QA_USER.NAME IS'用户名称';
COMMENT ON COLUMN QA_USER.PROCESS_CODE IS'站别代码';
COMMENT ON COLUMN QA_USER.PROCESS_SIGN IS'是否作业员,默认0是，1否';
COMMENT ON COLUMN QA_USER.VALID IS'是否有效，0有效，1无效';
COMMENT ON COLUMN QA_USER.CREATE_USER_ID IS'创建人id';
COMMENT ON COLUMN QA_USER.CREATE_TIME IS'创建时间';
COMMENT ON COLUMN QA_USER.MODIFY_TIME IS'修改时间';
/

create table REPAIR_RECORD
(
  ID NUMBER(20) default NULL not null
    constraint PK_REPAIR_RECORD
    primary key,
  PROCESS_RECORD_ID NUMBER(11),
  PRODUCT_ID VARCHAR2(80),
  BAD_CODE VARCHAR2(80),
  BAD_NAME VARCHAR2(200),
  BAD_TYPE VARCHAR2(80),
  BAD_RESON VARCHAR2(80),
  REPAIR NUMBER default 0,
  USER_ID VARCHAR2(80),
  CREATE_TIME DATE default SYSDATE,
  MODIFY_TIME DATE,
  REMARK VARCHAR2(100),
  REPAIR_PROCESS_CODE VARCHAR2(80)
);
COMMENT ON TABLE REPAIR_RECORD IS'维修内容';
COMMENT ON COLUMN REPAIR_RECORD.ID IS'主键';
COMMENT ON COLUMN REPAIR_RECORD.process_record_ID IS'测试记录ID';
COMMENT ON COLUMN REPAIR_RECORD.product_id IS'产品Id';
COMMENT ON COLUMN REPAIR_RECORD.BAD_CODE IS'不良代码';
COMMENT ON COLUMN REPAIR_RECORD.BAD_NAME IS'不良代码名称';
COMMENT ON COLUMN REPAIR_RECORD.BAD_TYPE IS'不良类型';
COMMENT ON COLUMN REPAIR_RECORD.BAD_RESON IS'不良原因';
COMMENT ON COLUMN REPAIR_RECORD.REPAIR IS'维修结果，0未维修1正常，2失败';
COMMENT ON COLUMN REPAIR_RECORD.user_id IS'维修人工号';
COMMENT ON COLUMN REPAIR_RECORD.CREATE_TIME IS'创建时间';
COMMENT ON COLUMN REPAIR_RECORD.MODIFY_TIME IS'修改时间';
COMMENT ON COLUMN REPAIR_RECORD.remark IS'备注';
/

create table QA_ROLE
(
  ID NUMBER(11) not null
    constraint PK_ROLE
    primary key,
  CODE VARCHAR2(80)
    constraint AK_UQ_ROLE_ROLE
    unique,
  NAME VARCHAR2(200),
  VALID NUMBER(1),
  DESCRIPTION VARCHAR2(200)
);

COMMENT ON TABLE Role IS'角色';
COMMENT ON COLUMN Role.ID IS'主键';
COMMENT ON COLUMN Role.CODE IS'角色代码';
COMMENT ON COLUMN Role.NAME IS'角色名称';
COMMENT ON COLUMN Role.VALID IS'0有效，1无效';
COMMENT ON COLUMN Role.DESCRIPTION IS'描述';
/

create table SN_INFO
(
  SN VARCHAR2(80) not null,
  TYPE VARCHAR2(20),
  CODE VARCHAR2(20),
  CATEGORY VARCHAR2(20) not null,
  YMD VARCHAR2(20),
  SERIAL_NUMBER VARCHAR2(20),
  PRODUCT_ID NUMBER(10),
  CREATE_TIME DATE default SYSDATE,
  ID NUMBER not null
    constraint SN_INFO_ID_PK
    primary key
);

COMMENT ON TABLE SN_INFO IS 'Sn信息，TYPE=CPSN,BLSN,BBSN';
COMMENT ON COLUMN SN_INFO.SN IS'sn';
COMMENT ON COLUMN SN_INFO.TYPE IS'编码类型';
COMMENT ON COLUMN SN_INFO.CODE IS'编码';
COMMENT ON COLUMN SN_INFO.CATEGORY IS'sn类别，chsn,blsn,bbsn';
COMMENT ON COLUMN SN_INFO.YMD IS'年月日，yymmdd';
COMMENT ON COLUMN SN_INFO.SERIAL_NUMBER IS'序列号，5位';
COMMENT ON COLUMN SN_INFO.PRODUCT_ID IS'产品ID';
/

create index SN_INFO__UK
  on SN_INFO (SN)
/

create table WORK_SHEET
(
  ID NUMBER(20) default NULL not null
    constraint PK_WORK_SHEET
    primary key,
  SHEET_NO VARCHAR2(80)
    constraint AK_UQ_WORK_SHEET_WORK_SHE
    unique,
  SHEET_PO VARCHAR2(80),
  PRODUCT_NO VARCHAR2(80),
  PRODUCT_TYPE_CODE VARCHAR2(80),
  TYPE NUMBER default 0,
  OUTPUT_NUM NUMBER(11),
  START_TIME DATE,
  END_TIME DATE,
  VALID NUMBER default 0,
  CREATE_TIME DATE default SYSDATE,
  CREATE_USER VARCHAR2(80)
);

COMMENT ON TABLE WORK_SHEET IS
  '工单';
COMMENT ON COLUMN WORK_SHEET.ID IS
  '主键';
COMMENT ON COLUMN WORK_SHEET.SHEET_NO IS
  '工单号';
COMMENT ON COLUMN WORK_SHEET.SHEET_PO IS
  '工单评审号';
COMMENT ON COLUMN WORK_SHEET.PRODUCT_NO IS
  '产品编号';
COMMENT ON COLUMN WORK_SHEET.PRODUCT_TYPE_CODE IS
  '产品类型';
COMMENT ON COLUMN WORK_SHEET.TYPE IS
  '0，导入 1,自编';
COMMENT ON COLUMN WORK_SHEET.OUTPUT_NUM IS
  '制单数量';
COMMENT ON COLUMN WORK_SHEET.START_TIME IS
  '开始时间';
COMMENT ON COLUMN WORK_SHEET.END_TIME IS
  '结束时间';
COMMENT ON COLUMN WORK_SHEET.VALID IS
  '是否有效，0有效，1无效';
COMMENT ON COLUMN WORK_SHEET.CREATE_TIME IS
  '创建时间';
COMMENT ON COLUMN WORK_SHEET.CREATE_USER IS
  '创建人';
/

create table QA_PREVIEW
(
  ID NUMBER(11) not null
    constraint PK_PREVIEW
    primary key,
  CODE VARCHAR2(80)
    constraint AK_UQ_PRIVIEW_CODE_PREVIEW
    unique,
  NAME VARCHAR2(80),
  URI VARCHAR2(200),
  VALID CHAR(10),
  DESCRIPTION VARCHAR2(200)
);

COMMENT ON TABLE preview IS
  '权限';
COMMENT ON COLUMN preview.code IS
  '代码';
COMMENT ON COLUMN preview.name IS
  '名称';
COMMENT ON COLUMN preview.uri IS
  '资源';
COMMENT ON COLUMN preview.valid IS
  '0有效，1无效';
COMMENT ON COLUMN preview.description IS
  '描述';
/

create table ROLE2PREVIEW
(
  ROLE_CODE VARCHAR2(80),
  PREVIEW_CODE VARCHAR2(80)
)
/

create table USER2ROLE
(
  USER_ID NUMBER(11),
  ROLE_CODE VARCHAR2(80)
);
COMMENT ON TABLE USER2ROLE IS '用户角色';
COMMENT ON COLUMN USER2ROLE.user_id IS '用户id';
COMMENT ON COLUMN USER2ROLE.role_code IS '角色代码';
/

create table BOM
(
  ID NUMBER(11) not null
    constraint PK_BOM
    primary key,
  PRODUCT_NO VARCHAR2(80),
  PRODUCT_TYPE_CODE VARCHAR2(80),
  TYPE NUMBER(1),
  NAME VARCHAR2(80),
  CODE VARCHAR2(80),
  SPEC VARCHAR2(400)
);

COMMENT ON TABLE BOM IS 'BOM';
COMMENT ON COLUMN BOM.id IS 'id';
COMMENT ON COLUMN BOM.product_Type_Code IS '产品类型';
COMMENT ON COLUMN BOM.type IS '类型，1说明数，2保修卡，3彩盒';
COMMENT ON COLUMN BOM.name IS '名称';
COMMENT ON COLUMN BOM.code IS '编码';
COMMENT ON COLUMN BOM.Spec IS '规格';
/

create table SYS_LOG
(
  ID NUMBER(20) not null,
  USER_ID NUMBER(11),
  PRODUCT_ID NUMBER(10),
  PRODUCT_LINE_CODE VARCHAR2(20),
  PROCESS_CODE VARCHAR2(20),
  CONTENT VARCHAR2(200),
  CREATE_TIME DATE default SYSDATE
);



/

